source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/sspAppTeam/SSSpecs.git'
install!'cocoapods',:deterministic_uuids=>false
use_frameworks!
platform :ios, '9.0'
inhibit_all_warnings!
target 'SSCoreOC_Example' do
  pod 'SSCoreOC', :path => '../'

  target 'SSCoreOC_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
